### ISSUE TITLE
EHEH-Eindhoven Airport-NOORD-BRABANT-NETHERLANDS

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#205]
Amsterdam

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21085725/cb8d6226-bfda-11e6-85e5-7a1cfbb879fa.png)

**Comment by MajorTomMueller** [comment]
Civ Apron was extended
New Engine test apron
Spawn sizes didn't fit real world usage in Mil part
Some pavement at buildings that where not hangars

Would you do @kilt46 , otherwise I would take over.

[EH-AD-2.EHEH-ADC.pdf](https://github.com/InfiniteFlightAirportEditing/Airports/files/3090637/EH-AD-2.EHEH-ADC.pdf)
[EH-AD-2.EHEH-APDC.pdf](https://github.com/InfiniteFlightAirportEditing/Airports/files/3090638/EH-AD-2.EHEH-APDC.pdf)

**Comment by MajorTomMueller** [comment]
![EHEH-git](https://user-images.githubusercontent.com/26853210/56497335-65447700-64fd-11e9-8b54-9da03348d01f.jpg)
