### ISSUE TITLE
KGEY-South Big Horn County Airport-WYOMING-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#2066]
I will do this. This base has over 10k feet runway so I think it isn't a low priority airport.

**Comment by DeafAviator** [comment]
Could someone please review my work on KLUF before I add the taxi line and buildings. This is my first airport so its probably messy.

[KLUF.zip](https://github.com/InfiniteFlightAirportEditing/Airports/files/1129769/KLUF.zip)

**Comment by alchonub** [comment]
Deaf Aviatior, do that with the apt.dat file in peer review

**Comment by DeafAviator** [comment]
apt. dat file of KLUF. I'm assuming you wanted the original file of KLUF and compare it to what I have right now.
[apt.zip](https://github.com/InfiniteFlightAirportEditing/Airports/files/1132622/apt.zip)

**Comment by dushyants19** [comment]
How is this going @DeafAviator

**Comment by DeafAviator** [comment]
I have been unable to work on it due to being busy with real life. I'm currently attending my college so I will be busy for while. I joined the airport editing team at bad time. I'm going to upload the latest work I have on KLUF here so it can be taken over. Apologize for not telling that I'm busy and I can't work on it anymore. @dushyants19

**Comment by DeafAviator** [comment]
[KLUF apt.zip](https://github.com/InfiniteFlightAirportEditing/Airports/files/1327829/KLUF.apt.zip)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35543160-3ade5290-0529-11e8-8425-c7d0d7b897ae.png)
