### ISSUE TITLE
GLRB-Roberts International-MARGIBI-LIBERIA

### ISSUE THREAD

**Issue by Tamz00** [InfiniteFlightAirportEditing/Airports#2352]
Part of Global Priority 2 (10k+ft Runway)

**Comment by dushyants19** [comment]
@JcFl4 his one has more spawns and taxiways don't overlap so... I'll revert your commits :)

**Comment by JcFl4** [comment]
Alright :/

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30943256-7529efa2-a3b5-11e7-9762-28b63017f901.png)

**Comment by brennanhackard** [comment]
This airport needs the following improvements to be made:

- unused taxiways need to be removed
- taxiways need to be adjusted around the apron due to construction of the new terminal
- markings need to be updated
- buildings need to be removed
- boundary needs to be moved
- frequencies need to be fixed
- airport name needs to be fixed
- spawn sizes need to be fixed

Be advised: The construction at this airport is not complete and scenery isn't amazing.

Reply to this comment below if you would like to be assigned.
