### ISSUE TITLE
KFSD-Joe Foss Field Airport-SOUTH DAKOTA-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#2527]
REUSE.

**Comment by brunocr98** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/issues/6

**Comment by brunocr98** [comment]
Please use the search bar before you create an issue. Thanks! :)

**Comment by dushyants19** [comment]
As mentioned in the thread on the community, it was was fixed. Please read the entire topic and we don't really need issues made by others since we actively keep an eye on the forum for issues with airports and take the required action. :)

https://community.infinite-flight.com/t/the-new-hardest-airport-in-if-found/165456/49?u=dush19

**Comment by rnorris03** [comment]
I'll do this

**Comment by brunocr98** [comment]
Maybe later, finish your other airports.

**Comment by rnorris03** [comment]
I've sent every other one in for review, do you want me to wait until they're approved?

**Comment by renorris** [comment]
Sent in for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36768460-eb52abac-1c04-11e8-8a34-157f955edd31.png)
