### ISSUE TITLE
MPRE-El Real Airport-DARIEN-PANAMA

### ISSUE THREAD

**Issue by grxninesix** [InfiniteFlightAirportEditing/Airports#2751]
♻️

**Comment by brunocr98** [comment]
I think we've been clear in your previous issue that we don't take suggestions from the public. Please refrain from doing this again.

**Comment by grxninesix** [comment]
WTF? I have never wrote « RECYCLE ME » What the f***???

I got emails about this thread but i never intented to, and never wrote that... What is the fffffff

**Comment by grxninesix** [comment]
But yeah thanks Kilt i saw the changes :)
I dont know why its not wrote « LSGY »? Because its actually about KDYS.... i am fully confused

**Comment by grxninesix** [comment]
Maybe it was unwanted operations during night because i saw my phone running while i woke up.. 😏
Sorry i have never intented to make this case open. The only things i remember is doing LSGY issue suggestion.

**Comment by grxninesix** [comment]
What was wrote before « RECYCLE ME »?

**Comment by brunocr98** [comment]
The reason of all this is because this was considered as unwanted. I've explained to you that we DO NOT take suggestions from outsiders. Therefore, I proceeded to close it and eventually it was recycled. I've done the changes you wanted, so there's really no need for you to be hanging around here. Plus, we already had a controversy with Swiss airports and we're certainly not looking forward a Season 2.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by mckenna27** [comment]
I would like to try my hand at working this issue.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62653564-2fa08e00-b934-11e9-9fe9-c3719bb566fc.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112703490-22b41380-8e65-11eb-984c-b7fc90788a91.png)
