### ISSUE TITLE
KVRB-Vero Beach Municipal-FLORIDA-USA

### ISSUE THREAD

**Issue by cboisselier** [InfiniteFlightAirportEditing/Airports#350]
_Reused_

**Comment by cboisselier** [comment]
Frequency modified

**Comment by Zimnaan** [comment]
Got it Clément. I am in charge of EHRD.

**Comment by cboisselier** [comment]
Already modified @Zimnaan

**Comment by dushyants19** [comment]
Continue discussion here -> https://github.com/InfiniteFlightAirportEditing/Airports/issues/310

**Comment by TristinWoolf** [comment]
Runway numbers written incorrectly, taxiways noticeably unsnapped, etc. Just a bunch of easy fixes, needs attention. Up for grabs!

**Comment by XRodriguezVB** [comment]
I'll work on this

**Comment by dushyants19** [comment]
Accept the invite :) (to join Github Team)

**Comment by IFAEpat** [comment]
@XRodriguezVB anything?

**Comment by XRodriguezVB** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Can't find anything.


Sent from Yahoo Mail for iPad


On Sunday, July 17, 2016, 5:12 PM, Patrick U <notifications@github.com> wrote:


@XRodriguezVB anything?

**Comment by TristinWoolf** [comment]
Unsnapped taxiways:
![image](https://cloud.githubusercontent.com/assets/18745517/16904222/2f3f6c94-4c57-11e6-8f0d-cd0ae0d7df6c.png)

Runway number written incorrectly ("4" instead of "04"):
![image](https://cloud.githubusercontent.com/assets/18745517/16904228/456523ce-4c57-11e6-867c-dfe477238408.png)

This may be possible buildings missing, as it looks like taxi lines that could be leading to hangars where there is currently grass:
![image](https://cloud.githubusercontent.com/assets/18745517/16904241/82a51bcc-4c57-11e6-83aa-c5786a2cc0c3.png)

**Comment by XRodriguezVB** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Okay thank you sooo much this helped a lot I'm new to this so thanks.


Sent from Yahoo Mail for iPad


On Sunday, July 17, 2016, 8:49 PM, Tristin Woolf <notifications@github.com> wrote:


Unsnapped taxiways:


Runway number written incorrectly ("4" instead of "04"):


This may be possible buildings missing, as it looks like taxi lines that could be leading to hangars where there is currently grass:

**Comment by TristinWoolf** [comment]
No problem. :)

**Comment by dushyants19** [comment]
how is this going?

**Comment by dushyants19** [comment]
@XRodriguezVB any progress?

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by dushyants19** [comment]
IF airport

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22392949/977817c4-e4c4-11e6-8283-13c968915e57.png)

**Comment by RyanEpps** [comment]
Airport needs reworked up to new standards and additional spawns.

**Comment by ChrisLevet232** [comment]
I would like to take this one if Kilt doesn't mind.

**Comment by ChrisLevet232** [comment]
Removed buildings, still touching up taxiways, lines, adding spawns and some other improvements to current standards. 

![kvrb](https://user-images.githubusercontent.com/30371438/50611383-22a25480-0ea4-11e9-8e65-550e102174bf.PNG)

**Comment by IFsami** [comment]
I can take this one

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93029399-393d0080-f5e0-11ea-8e90-78c51a51ed0f.png)
