### ISSUE TITLE
LSZB-Belp Airport-BERN-SWITZERLAND

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#677]
Bern Airport

**Comment by Yifan081** [comment]
I will do this one.

**Comment by NickArt1342** [comment]
This one is already done.
If you wouldn't have unassigned all my issues there would not be such problems right now.

**Comment by Yifan081** [comment]
Had it almost complete. May I be unassigned then?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24590449/dcb2b274-17b2-11e7-8da6-b85989059d06.png)

**Comment by kilt46** [comment]
2 x transparent pads!
![image](https://user-images.githubusercontent.com/14023167/27792329-d55df8cc-5fbe-11e7-87c7-5438d8b46a41.png)

**Comment by kilt46** [comment]
Also no lighting at airport

**Comment by NickArt1342** [comment]
Because there is no lighning apart from the one that are added already.

**Comment by moritzbabl** [comment]
ok, some friendly suggestions for this as well:

- manually drawn grass runway edge indicators are somewhere in nowhere, either remove or put grass below
- PAPI's are all facing 360°
- I'd assume a light called "PAPI LEFT" is not a VASI but a PAPI
- Ramp Operation Types are missing
- I'm quite certain spawns at Bern are not suitable for HEAVY JETS
- Ramp Start Types are not even touched
- PAPI angles are incorrect: https://fly.rocketroute.com/plates/adminview/LSZB_AERODROME_CHART.pdf?cmd=pdf&docid=400000000275272&icao=LSZB&_ga=2.23837182.577152129.1499117668-1572037586.1486043872

That's what I found in the first 5 minutes, no guarantee there isn't more

**Comment by bavAVIA** [comment]
Don't worry. I got this.
Btw, July 3rd.

**Comment by bavAVIA** [comment]
Dear @NickArt1342 ,

What you made right there is far beyond my previous limits of imagination, considering it was made by a supervisor. It's closer to Donezk Airport (which has been bombed and completely destroyed by russian seperatists) than it is to Bern. I wanted to fix the errors since you don't really seem to care about what we tell you, but **ended up redoing the entire airport from scratch**, that's how poor it is.

Before you start yelling at me again for taking your 'beautiful' airports, let me give you a quick summary of all the remarks I could find you would need to fix to get it close to current editing standards. Please keep in mind I might have not seen some because there are so many.

* Horrible / non-existant detailing work
* Incorrect Runway surface for 14/32
* A whole lot of spawns including respective lines are missing
* Missing taxiway edge lines for TWY Alpha
* **HORRIBLE** Taxiway layouts
* **HORRIBLE** taxiway line layouts
* Spawn names don't match 
* Missing Buildings
* Missing road markings
* Some spawns not snapped to lines
* Airport beacon in the middle of nowhere
* Runway 32 should have a PAPI light
* PAPI lights are orientated completely wrong
* Pitch angle relative to horizon of PAPI lights is wrong in both cases
* Runway markings incorrect on 14/32
* Approach lighting incorrect on 14/32
* Several light settings for 14/32 incorrect
* Since when do grass runways have approach lights and runway markings?
* Runway length incorrect for both runways
* Runway width incorrect for 14/32
* Many arbitralily placed windsocks
* Airport boundary inaccurate
* Incorrect equipment types for all spawns
* Missing Ramp Operation types for all spawns
* Missing Ramp Start types for all spawns
* Grass runway edge markings are redundant
* Turnpads Kilt has already reminded you of two days ago are still transparent
* One Tower frequency is not needed
* Missing Clearance Delivery Frequency
* Approach and Departure should be sperate frequencies in WED
* ...

The question I'm seriously wondering about is how you couldn't do better than **this** in exactly **400 days**, even more because you are a supervisor. I made my version within 4 hours. We have absolute newbies who do better from their first airport onwards. And since you already did all your airports, at least according to you, you should be very practiced. 
Let me give you an advice albeit I know you will only yell at me again for taking all your airports and not care whatsoever. Assign yourself to three airports, which is the limit just for everybody else here as well, do the airports, send them in for review and assign yourself to a new one once it has been approved. You're never going to meet up with the current standards if you just continue like this and Bern won't remain the only airport scratched and redone by somebody else since we simply can't utilize what you edit right there. 
Also, **use charts when editing airports!** Either ask Kilt for charts or browse the internet if you don't have a navigraph subscription or anything like that. You wouldn't have had a very good bunch of remarks from up there if you just looked at a chart.

I hope you at least took something I told you serious for once.
Regards.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27830948-457ed1d8-608e-11e7-89c0-47db949d8120.png)
