### ISSUE TITLE
FACT-Cape Town International Airport-WESTERN CAPE-SOUTH AFRICA

### ISSUE THREAD

**Issue by planemadnews** [InfiniteFlightAirportEditing/Airports#680]
Reworking FACT

**Comment by planemadnews** [comment]
Sent for Review

**Comment by planemadnews** [comment]
Sent in for approval

**Comment by AxelBeder** [comment]
Added to repro.

**Comment by JcFl4** [comment]
The FACT this airport is called FACT is funny...

**Comment by IFAEpat** [comment]
Better than KRAP @JcFl4

**Comment by JcFl4** [comment]
True! hahaha @IFAEpat

**Comment by planemadnews** [comment]
Has this been committed too?

**Comment by dushyants19** [comment]
Yes Caleb :scream:

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19417990/56ad4254-9380-11e6-9731-7320736026f7.png)

**Comment by ryu12332** [comment]
ISSUE: The taxiway lines are very inaccurately placed.
The lines do not go in a straight line, they are skew.
A lot of missing taxiway lines as well.
The runways in the real world are 01 (Instead of 34) , 19 (Instead of 16), 16 (instead of 13) and 34 (instead of 31). 
[IMAGES](https://drive.google.com/drive/folders/1AdazmhYxopl-KkxVG-43dC24qFlLB9TR)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34961328-61d6f058-fa04-11e7-8e57-c192ee686e93.png)
