### ISSUE TITLE
ELLX-Luxembourg Airport-LUXEMBOURG-LUXEMBOURG

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#727]
Luxembourg Findel Airport.

**Comment by kilt46** [comment]
Incorrect parking. Please use this
![image](https://cloud.githubusercontent.com/assets/14023167/16179699/6bd9bf22-3633-11e6-9729-b5a70380e845.png)

**Comment by henrikbg** [comment]
Gates have been fixed.

**Comment by kilt46** [comment]
Details of main apron look a little off. No curves and building definition poor
![image](https://cloud.githubusercontent.com/assets/14023167/16325740/4dea3af4-3986-11e6-898c-3a8b74c90067.png)

**Comment by TristinWoolf** [comment]
It looks as if this issue was created with intentions of being a suggestion, as @Aviationluver never stated that he actually wanted to redo it. It was mistakingly assumed that he did, which is no big deal, so it appears to not actually have been redone, thus having issues with incorrect gates in the first place. 
Phillipp can correct me if I'm wrong, which if I am, we will properly reassign him to this issue, but for now the issue has become open to anyone who wants to take this on. It appears in the picture that the airport needs an overhaul or possibly a complete redo.

1. Taxiways
- Some taxiways may be misaligned and have improper light/line attributes; Border lights appear to be on the inside instead of the outside.
- Service roads look to be placed incorrectly throughout the airport and need adjusting.
2. Taxi lines and spawn points
- Parking areas may have incorrectly placed parking spots. This goes along with spawn points as well. (Although it appears that Henrik might have adjusted that, but it's hard to tell.)
3. Buildings
- Buildings seem to have been improperly placed and shaped. 

This is currently open for anyone to look into! :)

**Comment by Aviationluver** [comment]
@TristinWoolf Yes I wanted to do this airport.

**Comment by TristinWoolf** [comment]
Alright, I will reassign you @Aviationluver Just please state if _you_ are redoing the airport when you create the issue, just to clear up any confusion. Happy editing! :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20286791/4eafd3b2-aa8e-11e6-8ca7-2187154ac0ce.png)

**Comment by moritzbabl** [comment]
Runway turnoffs are lacking centerlines, needs a little update, GA apron was updated as well

**Comment by MajorTomMueller** [comment]
Latest AIP:
https://ops.skeyes.be/html/belgocontrol_static/eaip/eAIP_Main/html/eAIP/EB-AD-2.ELLX-en-GB.html
